class CreatePolicies < ActiveRecord::Migration
  def change
    create_table :policies do |t|

      t.string :policy_number, default: ""
      t.string :status, default: ""
      t.string :client_code, default: ""
      t.string :name, default: ""

      #t.date :effective_date, default: '1995-11-08'
      #t.date :expiration_date, default: '1995-11-08'

      t.string :forms, default: ""
      t.string :property_forms, default: ""
      t.string :gl_forms, default: ""
      t.string :crime_forms, default: ""
      t.string :auto_forms, default: ""

      #t.integer :package_premium_total, default: 0

      t.string :A, default: ""
      t.date :B, default: '1995-11-08'
      t.date :C, default: '1995-11-08'
      t.string :D, default: ""
      t.string :E, default: ""
      t.string :F, default: ""
      t.string :G, default: ""
      t.string :H, default: ""
      t.string :I, default: ""
      t.string :J, default: ""
      t.string :K, default: ""
      t.string :L, default: ""
      t.string :M, default: ""
      t.string :N, default: ""
      t.string :O, default: ""
      t.string :P, default: ""
      t.string :Q, default: ""
      t.string :R, default: ""
      t.string :S, default: ""
      t.string :T, default: ""
      t.string :U, default: ""
      t.string :V, default: ""
      t.string :W, default: ""
      t.string :X, default: ""
      t.string :Y, default: ""
      t.string :Z, default: ""
      t.string :AA, default: ""
      t.string :AB, default: ""
      t.string :AC, default: ""
      t.string :AD, default: ""
      t.string :AE, default: ""
      t.string :AF, default: ""
      t.string :AG, default: ""
      t.string :AH, default: ""
      t.string :AI, default: ""
      t.string :AJ, default: ""
      t.string :AK, default: ""
      t.string :AL, default: ""
      t.string :AM, default: ""
      t.string :AN, default: ""
      t.string :AO, default: ""
      t.string :AP, default: ""
      t.string :AQ, default: ""
      t.string :AR, default: ""
      t.string :AS, default: ""
      t.string :AT, default: ""
      t.string :AU, default: ""
      t.string :AV, default: ""
      t.string :AW, default: ""
      t.string :AX, default: ""
      t.string :AY, default: ""
      t.string :AZ, default: ""
      t.string :BA, default: ""
      t.string :BB, default: ""
      t.string :BC, default: ""
      t.string :BD, default: ""
      t.string :BE, default: ""
      t.string :BF, default: ""
      t.string :BG, default: ""
      t.string :BH, default: ""
      t.string :BI, default: ""
      t.string :BJ, default: ""
      t.string :BK, default: ""
      t.string :BL, default: ""
      t.string :BM, default: ""
      t.string :BN, default: ""
      t.string :BO, default: ""
      t.string :BP, default: ""
      t.string :BQ, default: ""
      t.string :BR, default: ""
      t.string :BS, default: ""
      t.string :BT, default: ""
      t.string :BU, default: ""
      t.string :BV, default: ""
      t.string :BW, default: ""
      t.string :BX, default: ""
      t.string :BY, default: ""
      t.string :BZ, default: ""
      t.string :CA, default: ""
      t.string :CB, default: ""
      t.string :CC, default: ""
      t.string :CD, default: ""
      t.string :CE, default: ""
      t.string :CF, default: ""
      t.string :CG, default: ""
      t.string :CH, default: ""
      t.string :CI, default: ""
      t.string :CJ, default: ""
      t.string :CK, default: ""
      t.string :CL, default: ""
      t.string :CM, default: ""
      t.string :CN, default: ""
      t.string :CO, default: ""
      t.string :CP, default: ""
      t.string :CQ, default: ""
      t.string :CR, default: ""
      t.string :CS, default: ""
      t.string :CT, default: ""
      t.string :CU, default: ""
      t.string :CV, default: ""
      t.string :CW, default: ""
      t.string :CX, default: ""
      t.string :CY, default: ""
      t.string :CZ, default: ""
      t.string :DA, default: ""
      t.string :DB, default: ""
      t.string :DC, default: ""
      t.string :DD, default: ""
      t.string :DE, default: ""
      t.string :DF, default: ""
      t.string :DG, default: ""
      t.string :DH, default: ""
      t.string :DI, default: ""
      t.string :DJ, default: ""
      t.string :DK, default: ""
      t.string :DL, default: ""
      t.string :DM, default: ""
      t.string :DN, default: ""
      t.string :DO, default: ""
      t.string :DP, default: ""
      t.string :DQ, default: ""
      t.string :DR, default: ""
      t.string :DS, default: ""
      t.string :DT, default: ""
      t.string :DU, default: ""
      t.string :DV, default: ""
      t.string :DW, default: ""
      t.string :DX, default: ""
      t.string :DY, default: ""
      t.string :DZ, default: ""
      t.string :EA, default: ""
      t.string :EB, default: ""
      t.string :EC, default: ""
      t.string :ED, default: ""
      t.string :EE, default: ""
      t.string :EF, default: ""
      t.string :EG, default: ""
      t.string :EH, default: ""
      t.string :EI, default: ""
      t.string :EJ, default: ""
      t.string :EK, default: ""
      t.string :EL, default: ""
      t.string :EM, default: ""
      t.string :EN, default: ""
      t.string :EO, default: ""
      t.string :EP, default: ""
      t.string :EQ, default: ""
      t.string :ER, default: ""
      t.string :ES, default: ""
      t.string :ET, default: ""

      t.timestamps null: false
    end

    add_index :policies, :policy_number, unique: true
    add_reference :policies, :broker, index: true, foreign_key: true
  end
end

=begin
one day we may get better code, but that day is not today.
t.string :A, default: ""
t.date :B, default: '1995-11-08'
t.date :C, default: '1995-11-08'
t.string :D, default: ""
t.string :E, default: ""
t.string :F, default: ""
t.string :G, default: ""
t.string :H, default: ""
t.string :I, default: ""
t.string :J, default: ""
t.decimal :K, default: 0
t.string :L, default: ""
t.string :M, default: ""
t.string :N, default: ""
t.string :O, default: ""
t.string :P, default: ""
t.string :Q, default: ""
t.string :R, default: ""
t.decimal :S, default: 0
t.decimal :T, default: 0
t.decimal :U, default: 0
t.string :V, default: ""
t.string :W, default: ""
t.decimal :X, default: 0
t.decimal :Y, default: 0
t.decimal :Z, default: 0
t.decimal :AA, default: 0
t.decimal :AB, default: 0
t.decimal :AC, default: 0
t.decimal :AD, default: 0
t.string :AE, default: ""
t.string :AF, default: ""
t.string :AG, default: ""
t.string :AH, default: ""
t.string :AI, default: ""
t.decimal :AJ, default: 0
t.string :AK, default: ""
t.string :AL, default: ""
t.decimal :AM, default: 0
t.string :AN, default: ""
t.decimal :AO, default: 0
t.string :AP, default: ""
t.decimal :AQ, default: 0
t.decimal :AR, default: 0
t.decimal :AS, default: 0
t.string :AT, default: ""
t.decimal :AU, default: 0
t.decimal :AV, default: 0
t.decimal :AW, default: 0
t.decimal :AX, default: 0
t.decimal :AY, default: 0
t.string :AZ, default: ""
t.decimal :BA, default: 0
t.decimal :BB, default: 0
t.decimal :BC, default: 0
t.decimal :BD, default: 0
t.decimal :BE, default: 0
t.decimal :BF, default: 0
t.decimal :BG, default: 0
t.decimal :BH, default: 0
t.decimal :BI, default: 0
t.decimal :BJ, default: 0
t.decimal :BK, default: 0
t.string :BL, default: ""
t.string :BM, default: ""
t.decimal :BN, default: 0
t.decimal :BO, default: 0
t.decimal :BP, default: 0
t.string :BQ, default: ""
t.decimal :BR, default: 0
t.string :BS, default: ""
t.decimal :BT, default: 0
t.decimal :BU, default: 0
t.decimal :BV, default: 0
t.string :BW, default: ""
t.decimal :BX, default: 0
t.string :BY, default: ""
t.decimal :BZ, default: 0
t.decimal :CA, default: 0
t.decimal :CB, default: 0
t.string :CC, default: ""
t.string :CD, default: ""
t.decimal :CE, default: 0
t.decimal :CF, default: 0
t.decimal :CG, default: 0
t.decimal :CH, default: 0
t.decimal :CI, default: 0
t.decimal :CJ, default: 0
t.decimal :CK, default: 0
t.string :CL, default: ""
t.decimal :CM, default: 0
t.string :CN, default: ""
t.decimal :CO, default: 0
t.string :CP, default: ""
t.string :CQ, default: ""
t.decimal :CR, default: 0
t.decimal :CS, default: 0
t.string :CT, default: ""
t.decimal :CU, default: 0
t.decimal :CV, default: 0
t.decimal :CW, default: 0
t.decimal :CX, default: 0
t.string :CY, default: ""
t.string :CZ, default: ""
t.decimal :DA, default: 0
t.decimal :DB, default: 0
t.string :DC, default: ""
t.decimal :DD, default: 0
t.decimal :DE, default: 0
t.decimal :DF, default: 0
t.decimal :DG, default: 0
t.decimal :DH, default: 0
t.decimal :DI, default: 0
t.decimal :DJ, default: 0
t.decimal :DK, default: 0
t.decimal :DL, default: 0
t.decimal :DM, default: 0
t.decimal :DN, default: 0
t.string :DO, default: ""
t.decimal :DP, default: 0
t.decimal :DQ, default: 0
t.decimal :DR, default: 0
t.decimal :DS, default: 0
t.decimal :DT, default: 0
t.decimal :DU, default: 0
t.decimal :DV, default: 0
t.decimal :DW, default: 0
t.string :DX, default: ""
t.decimal :DY, default: 0
t.decimal :DZ, default: 0
t.string :EA, default: ""
t.decimal :EB, default: 0
t.decimal :EC, default: 0
t.string :ED, default: ""
t.decimal :EE, default: 0
t.decimal :EF, default: 0
t.decimal :EG, default: 0
t.decimal :EH, default: 0
t.decimal :EI, default: 0
t.string :EJ, default: ""
t.decimal :EK, default: 0
t.string :EL, default: ""
t.string :EM, default: ""
t.string :EN, default: ""
t.decimal :EO, default: 0
t.string :EP, default: ""
t.string :EQ, default: ""
t.string :ER, default: ""
t.string :ES, default: ""
t.string :ET, default: ""
=end
